import { GeneratedFile } from '@/types';

export function getDefaultPackageJson(projectId: string): string {
  return JSON.stringify({
    name: `project-${projectId}`,
    version: "0.1.0",
    private: true,
    scripts: {
      "dev": "next dev",
      "build": "next build",
      "start": "next start",
      "lint": "next lint",
      "test": "jest",
      "test:watch": "jest --watch"
    },
    dependencies: {
      "react": "^19.0.0",
      "react-dom": "^19.0.0",
      "next": "^15.1.0",
      "lucide-react": "^0.468.0"
    },
    devDependencies: {
      "typescript": "^5.7.2",
      "@types/node": "^22.10.1",
      "@types/react": "^19.0.1",
      "@types/react-dom": "^19.0.1",
      "postcss": "^8.4.49",
      "tailwindcss": "^3.4.16",
      "autoprefixer": "^10.4.20",
      "eslint": "^9.16.0",
      "eslint-config-next": "^15.1.0",
      "jest": "^29.7.0",
      "jest-environment-jsdom": "^29.7.0",
      "@testing-library/react": "^16.1.0",
      "@testing-library/jest-dom": "^6.6.3",
      "ts-jest": "^29.2.5",
      "@types/jest": "^29.5.14"
    }
  }, null, 2);
}

export function getDefaultTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: "es5",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [
        {
          name: "next"
        }
      ],
      paths: {
        "@/*": ["./src/*"]
      }
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"]
  }, null, 2);
}

export function getDefaultTailwindConfig(): string {
  return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
}
`;
}

export function getDefaultPostcssConfig(): string {
  return `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
}

export function getDefaultNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
`;
}

export function getDefaultJestConfig(): string {
  return `const nextJest = require('next/jest')

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
})

// Add any custom config to be passed to Jest
const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testEnvironment: 'jest-environment-jsdom',
  moduleNameMapper: {
    // Handle module aliases (this will be configured automatically)
    '^@/(.*)$': '<rootDir>/src/$1',
  },
}

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
module.exports = createJestConfig(customJestConfig)
`;
}

export function getDefaultJestSetup(): string {
  return `import '@testing-library/jest-dom'\n`;
}

export function getDefaultGlobalsCss(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
`;
}

export function getDefaultLayout(): string {
  return `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Collabro AI Project',
  description: 'Generated by Collabro AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`;
}

export function getDefaultPage(): string {
  return `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
        <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
          Get started by editing&nbsp;
          <code className="font-bold">src/app/page.tsx</code>
        </p>
      </div>
    </main>
  )
}
`;
}

export function getDefaultNextJsFiles(projectId: string): GeneratedFile[] {
  const timestamp = Date.now();
  const agent = 'manager';
  return [
    { path: 'package.json', content: getDefaultPackageJson(projectId), agent, generatedAt: timestamp },
    { path: 'tsconfig.json', content: getDefaultTsConfig(), agent, generatedAt: timestamp },
    { path: 'tailwind.config.js', content: getDefaultTailwindConfig(), agent, generatedAt: timestamp },
    { path: 'postcss.config.js', content: getDefaultPostcssConfig(), agent, generatedAt: timestamp },
    { path: 'next.config.js', content: getDefaultNextConfig(), agent, generatedAt: timestamp },
    { path: 'jest.config.js', content: getDefaultJestConfig(), agent, generatedAt: timestamp },
    { path: 'jest.setup.js', content: getDefaultJestSetup(), agent, generatedAt: timestamp },
    { path: 'src/app/globals.css', content: getDefaultGlobalsCss(), agent, generatedAt: timestamp },
    { path: 'src/app/layout.tsx', content: getDefaultLayout(), agent, generatedAt: timestamp },
    { path: 'src/app/page.tsx', content: getDefaultPage(), agent, generatedAt: timestamp }
  ];
}
